### ISSUE TITLE
Remove mandatory `pyam` dependency

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#109]

**Comment by znicholls** [comment]
Sorry @swillner, could you give a bit more context? Would the plan be to move this into an optional dependency (either in notebooks or a new 'extras' target such as 'analysis')?

**Comment by swillner** [comment]
Yes, that would be good to have it optional. It's quite a heavy dependency and you are going to make `ScmDataFrame` independent, anyway, isn't it?

**Comment by znicholls** [comment]
> you are going to make `ScmDataFrame` independent, anyway, isn't it?

Maybe, I'm not sure whether we'll go completely independent or not. Let's see how @lewisjared and I go with that and if we can make it optional we will.

**Comment by swillner** [comment]
Great! Would hope we can make it optional ;)

**Comment by lewisjared** [comment]
It would be simple enough to make it independent. It would require some duplicating some code which currently lives in pyam
