### ISSUE TITLE
Define standard file format

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#11]
For handling things like running multiple models in multiple scenarios should we:

a) use `xarray` and have a 'scenario' and a 'model' dimension
b) use `pd.DataFrame` in long form (so we'd have a model column, a scenario column and hence have to repeat the years once per model-scenario column combination)
c) do something else

??

**Comment by znicholls** [comment]
@chrisroadmap what were the roadblocks with `xarray`?

**Comment by chrisroadmap** [comment]
I wanted to read in an RCP file using `pandas`, parse the units and attach
the units to each column (before getting started with `pint`).  The other
thing I wanted to do was change the year column to the index. `xarray`
seemed reluctant to let me do this. I'm sure all of this is doable but I
couldn't figure it out.

**Comment by znicholls** [comment]
ok. Given the last comment on xarray's units issue was 2 years ago (https://github.com/pydata/xarray/issues/525) and that we're nearly there (kind of) with pandas and pint plus the fact that pint has contexts which would allow us to add GWP/GTP conversions, I'm going to suggest we press ahead with pandas as our interface (in long form without an index to make life easy, then we offer some method like 'stack_sensible' to get back a dataframe with a time index and multiple column headers for e.g. 'model', 'scenario', 'ecs' etc.) with pint arrays as our base datatype.

Any objections?

**Comment by znicholls** [comment]
@chrisroadmap @rgieseke @swillner @JGuetschow @mljeffery agree/disagree on the following?

For our standard data format, we copy the format in pymagicc. This consists of a custom object which has two key attributes, `df` - the pandas dataframe holding the data and `metadata` - a dictionary which holds the metadata. This is not a perfect solution to the metadata problem but is the best I've seen so far.

**Comment by swillner** [comment]
I would very much favor a language-agnostic format, so having an array-like datastructure accompanied by metadata about size/units/... sounds good. The latter in yaml/json when serialized would also easily allow to extend the datapackage standard for scenario files... Shall we have a meeting about API and data structures next week?

**Comment by znicholls** [comment]
> Shall we have a meeting about API and data structures next week?

Sounds good to me!

**Comment by rgieseke** [comment]
We might need something for people to feed and read from their GAMS or C++ models probably -- so having CSV+JSON metadata Data Packages is probably an option :-)

Next week meeting sounds good!

**Comment by znicholls** [comment]
Thinking about it more, it might be a good idea to build on top of the [pyam](https://github.com/IAMconsortium/pyam) dataframe. They've done some really nice stuff with filtering and aggregating (and checking those aggregations) that makes life much easier. Our simple addition could be the `metadata` attribute.

**Comment by JGuetschow** [comment]
Aggregation and filtering would be really useful. I also thought about data structures for a possible successor of the PRIMAP emissions module, but coded nothing so far. But if you're interested I could explain, what my ideas are.

**Comment by znicholls** [comment]
Ye if you have a bullet point summary add them in, then we can hopefully
design something good!

**Comment by mljeffery** [comment]
It was less well planned than pyam or Johannes ideas, but for a couple of papers I've also had to write some code that deals with the AR5 and SSP scenario databases. The 'SSP-scenario-explorer' is in a PIK Gitlab repository and might be worth looking at for ideas of how (not) to proceed. 

@znicholls - do you have access to PIK Gitlab?

**Comment by znicholls** [comment]
> @znicholls - do you have access to PIK Gitlab?

No idea (which probably means no?).

When you say 'deals with', what do you mean? Is it perhaps now handled by https://github.com/IAMconsortium/pyam

**Comment by mljeffery** [comment]
> > @znicholls - do you have access to PIK Gitlab?
> 
> No idea (which probably means no?).
then probably not, no. 

The 'explorer' part is in many ways similar to pyam, and pyam may well be cleaner but I need to look at it a bit more first. 

For other work though I've gone a step further and performed more manipulation on the data, e.g. calculating cumulative emissions. Some of the output is in [this paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018EF000865) and I have intentions of cleaning up the code and making it available... This week is already a bit hectic though.

**Comment by znicholls** [comment]
> I have intentions of cleaning up the code and making it available

I would be tempted to try and put that in as pull requests to `pyam` rather than have multiple packages. Giving responsibility for dealing with data formats to the people who make it seems a good idea to me.

**Comment by JGuetschow** [comment]
I think pyam looks like a step into the right direction, but without checking the code I can't tell it it's general enough to be used as a basis for what I would like to do. My idea is the following:

The data we work with is basically always organized in time series. One could of course understand the data as multi-dimensional arrays where one dimension is time and other dimensions are gas, unit, scenario, sector, country, etc. However, this would lead to a structure that is very high-dimensional but most dimensions are very scarcely populated. Also, all dimensions apart from don't have a meaningful linear ordering and are rather a collection of values than a meaningful coordinate. Thus I think it makes sense to use a time-series as the basic unit for computations. All variables like sectors, gas, country would then be metadata information of the time series. 
For computations I would collect several such time series in a structure derived from a pandas DataFrame. The DataFrame can already handle multiple headers, so the variables can be included as headers. However, this is not very efficient if the value of a certain variable is the same for all time series in a DataFrame. For this case I would add metadata to the DataFrame which holds the header variables which are constant among the contained time series. All operations would need to respect this structure and modify variables in both places and move them to the appropriate place e.g. in case of selection of a subset of time series or combination of multiple DataFrames.
The operations visible to the user would not need any knowledge about the place of a variable. They would be defined such that we say e.g. sum CO2, CH4, N2O, FGASES to KYOTOGHG. The operation would then find groups of tables for the given gases which are identical in all other header variables and combine them to a KYOTOGHG table. 
Such definitions of are independent of the actual data structure in memory and could work in the same way on data in long format (i.e. only one data point per row / column and time as a header variable) e.g. for data in a SQL database.

**Comment by znicholls** [comment]
@JGuetschow I think your problem has already been solved by pandas `MultiIndex`. As far as I can tell it stores everything as sparsely as possible. I think trying to optimise above what pandas has done seems like early optimisation to me (I've never run into a problem where keeping an extra sector column was a problem...) and feel we'd be better off adding into the pandas framework rather than trying to build our own?

**Comment by JGuetschow** [comment]
I know the MultiIndex, but thought for the many header fields we would have it would be a bit too much, to put them all in the index. But maybe it can be dealt with by just hiding them when displaying or exporting the data. My intention was to build on pandas, not to rewrite something similar from scratch.

**Comment by znicholls** [comment]
ah ok apologies I misunderstood

yes I think you can do some nice things with how you represent your fields (@rgieseke has played around a bit) and then also some custom ways to save could help!

**Comment by swillner** [comment]
Replaced by #106
