### ISSUE TITLE
Use parts of Collective Code Construction Contract?

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#115]
The Collective Code Construction Contract ("C4") (see https://rfc.zeromq.org/spec:42/C4/ and, for a commented version, https://hintjens.gitbooks.io/social-architecture/content/chapter4.html) has some good ideas to organize development.

In particular, I would propose to only have a master branch in this repository and disallow further feature branches (C4: "The project SHALL NOT use topic branches for any reason. Personal forks MAY use topic branches.") as this repository is becoming a mess (granted, we are still in the process of settup up the OpenSCM skeleton).

@rgieseke @znicholls @lewisjared Thoughts?

**Comment by swillner** [comment]
(would also remove the need for "sandbox" PRs ;) )

**Comment by rgieseke** [comment]
Advantage now: everyone sees what's going on.
Disadvante now: hard to see what's going on if too much is going on ...

Not sure if we are at the stage where it's impossible to manage (ZeroMQ is/was probably much bigger when they made this decision) -- not having PRs which are never going to be merged is probably a good idea though …

**Comment by swillner** [comment]
I don't have the feeling that having branches not belonging to PRs helps seeing what's going on... It's still hidden in those branches.

**Comment by rgieseke** [comment]
Not sure i understand, topic branches can be bug fixes or features or experimental - i'd agree to only have branches that are (potentially) merged,

**Comment by swillner** [comment]
I mean if it's a PR anyway, regarding knowing what's going on it does not matter where the corresponding branch is

**Comment by znicholls** [comment]
Im happy with whatever you decide on this one. My guess would be that forks
are cleaner but increase the risk of duplicating work.

**Comment by rgieseke** [comment]
I also like that it's easy to push to someone else's PR when we sit together on one machine or in a chat/call - with forks you would have to grant permissions every time, right?

**Comment by znicholls** [comment]
> I also like that it's easy to push to someone else's PR when we sit together on one machine or in a chat/call

This would actually be a reason to use forks for me, pushing to other people's branches is dangerous if they rebase...

**Comment by rgieseke** [comment]
> This would actually be a reason to use forks for me, pushing to other people's branches is dangerous if they rebase...

I just meant when one does a PR review together and it's easier to just fix things in an editor ...

**Comment by znicholls** [comment]
> I just meant when one does a PR review together and it's easier to just fix things in an editor ...

ah, my bad

**Comment by swillner** [comment]
What about:

1. Major feature branches (such as ``scmcalib``) in the openscm-repository, which are only worked on via PRs from forks.
2. Branches that are directly worked on in forks.
3. Once starting to work on such a branch make a PR and label it "WIP" and, if not to be merged on master, name it "<TARGETBRANCH>: ..." and label it "not-master"
4. Remove the "WIP" label once the branch is ready to be merged.

**Comment by znicholls** [comment]
Sounds good.

To be clear, the `scmcallib` branch should never be merged. It's a first draft so @lewisjared and I can see how it plays with the `scmcallib` package but, given our other discussions, the implementation is wrong.
