### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#116]
Hi @znicholls @lewisjared 
I've deleted the PyPI 0.0.0 release - i think we should wait with that until we have a proper release and tag.
For testing (e.g. in other projects) one could use direct installation from GitHub, for testing the packaging process we could use the TestPyPI instance.

We could also consider using Travis to automatically upload tagged releases (when tests pass) to PyPI.

**Comment by znicholls** [comment]
> I've deleted the PyPI 0.0.0 release - i think we should wait with that until we have a proper release and tag

Cool, I only put it up to reserve the namespace on pypi.

**Comment by rgieseke** [comment]
Awesome -- the auto deployment could be done something like this:

https://github.com/simonw/dbf-to-sqlite/blob/master/.travis.yml#L25

**Comment by swillner** [comment]
Should be working now using the Github Actions workflow (see documentation in #132). Keeping this open as part of the "First working pre-release" milestone.
