### ISSUE TITLE
Other similar repos

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#12]
MAAT

Paper https://www.geosci-model-dev.net/11/3159/2018/gmd-11-3159-2018.pdf
GitHub https://github.com/walkeranthonyp/MAAT

If someone can explain what this is doing that would be ideal

**Comment by swillner** [comment]
Hmm, as I understand it, it's a framework, which helps you i) define and develop a model and ii) run/evaluate it for an ensemble of input parameters. I do not think it is very related to `OpenSCM` as it has a much wider scope regarding models and a narrower one in the sense that it is not about comparability between models but in parameters for a specific model.

I like their paragraph on "Use guidelines":
```
If you want to use this code then please do! If you plan to publish using this code the please be respectful of other people's work and their willingness to open source their code. If you are using recent modifications and code updates, please be aware that the author of these developments may not have yet published what they are intending to, please contact them to discuss. Older code is fine to use without co-authorship, but it is rcommended that code authors be contacted. This is a balance, and likely no single rule really fits all situations, communicating your intentions at an early stage (i.e. during the early stages of a study before manuscript drafting) is the policy.
```
;)

**Comment by znicholls** [comment]
> I like their paragraph on "Use guidelines"

Shall we bring it into our use guidelines?

**Comment by swillner** [comment]
Should actually be the standard way in academia ;)
I am just astonished that somebody really spelled it out what many people in academia are afraid of when open sourcing their code ;)

**Comment by znicholls** [comment]
> I am just astonished that somebody really spelled it out what many people in academia are afraid of when open sourcing their code

It's good, let's put it in ours too
