### ISSUE TITLE
Adapter: DICE climate component

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#13]
**Is your feature request related to a problem? Please describe.**

Given the findings of (Calel and Stainforth)[https://journals-ametsoc-org.ezp.lib.unimelb.edu.au/doi/10.1175/BAMS-D-16-0034.1], it would be nice to add simple models like the ones used in PAGE, FUND and DICE into the mix. You could do simple things like speed comparisons as well as performance comparisons etc. 

**Describe the solution you'd like**

Add the ability to run the models described above into the mix. 

**Describe alternatives you've considered**

None.

**Additional context**

These are easy wins given the models are so simple.

**Comment by rgieseke** [comment]
@swillner you looked at DICE et al. -- any thoughts on a simple Python implementation, want to contribute your C++ version?

**Comment by swillner** [comment]
will do ;)

**Comment by swillner** [comment]
Handled in #41
