### ISSUE TITLE
Miscellaneous parameter type

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#143]
**Is your feature request related to a problem? Please describe.**

Modellers choose to set parameters in all sorts of odd ways e.g. MAGICC has parameters which are vectors but not timeseries and lists of strings, FaIR has matrices which are not timeseries. We should support these.

**Describe the solution you'd like**

Given that we can't anticipate what modellers will choose nor do we want to prescribe that, adding a parameter class called 'Misc' which allows the user to pass any value in, but does not support other operations such as aggregation to higher levels seems like a good option.

**Describe alternatives you've considered**

We could custom implement all of these types. However that seems to add a number of extra parameter classes and complexity for almost zero reward.

**Additional context**

Carried over from #142

**Comment by swillner** [comment]
What is the exact specification here for these in MAIGCC and FaIR?

**Comment by znicholls** [comment]
MAGICC has stuff like `EMMS_2SCEN_REGIONS = [0.1, 0.3, 0.15, 0.25, 0.2]` and `MHALO_FGAS_NAMES = ["CFC11", "CFC12",.... ]` whilst FaIR has stuff like `ecs = 765 x 2 dimensional array`

**Comment by swillner** [comment]
Constant/variable length? What types in the vectors/lists/arrays? What other requirements do these values have?

**Comment by znicholls** [comment]
MAGICC ones are constant length, FaIR ones aren't. `EMMS_2SCEN_REGIONS` is floats, `MHALO_FGAS_NAMES` is strings, `ecstcr` is floats. MAGICC has other parameters which are lists of ints. Some parameters have a requirement that the sum should be equal to 1. 

My point here is that we're not going to want to program every idea that people have (a lot of them are to be frank bizarre but fixing models is not the remit of this project) and so we should just offer a catch all solution for these outlying cases.

**Comment by swillner** [comment]
Do they have units? And if so, are all units the same in an array? If not, I agree, otherwise we should at least have a generic array type.
Do you know of any models that share such "misc parameters"?

**Comment by znicholls** [comment]
> Do they have units?

Sometimes (e.g. `ecstcr` does, `EMMS_2SCEN_REGIONS` is dimensionless).

> And if so, are all units the same in an array?

Yes.

> we should at least have a generic array type.

That's probably wise, on top of a generic type and the boolean and string types? What do we gain from supporting 6 types rather than just timeseries, scalar, other i.e. 3 types?

> Do you know of any models that share such "misc parameters"?

No I think these sort of weird generic parameters would always be special case rather than shared/part of any standard.

**Comment by swillner** [comment]
> What do we gain from supporting 6 types rather than just timeseries, scalar, other i.e. 3 types?

I mean, if the array has units, we can at least provide the conversion. So: timeseries, scalar, array, other.

**Comment by swillner** [comment]
We could also, of course, just merge scalar & array then

**Comment by znicholls** [comment]
I think I'd prefer to start generic, then make more specific use cases when it makes sense, than start with specific cases before adding generic. Having said that, it might be possible that all we actually need is timeseries, array (assuming array can handle scalar too), other (i.e. everything that doesn't have units so can't benefit from internal unit conversion). Thoughts?

**Comment by swillner** [comment]
Sounds good.

**Comment by swillner** [comment]
@znicholls Currently working on the DICE adapter and it looks like we need some typing fixes in the Core, anyway. Ok, if I replace bool/str parameter types by the generic in that?

**Comment by znicholls** [comment]
sounds good to me
