### ISSUE TITLE
Discussion: variable names

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#15]
@chrisroadmap @rgieseke @swillner @JGuetschow @mljeffery

We need to work out some convention for how we name our variables in this common interface. I would propose following MAGICC's conventions, with some improvements to make things clearer. (However these are only proposals I haven't really thought through, happy to use all of your learnings and choose better conventions!) 

Anyway, I propose the following format:

`[variable]_[variable-type]_[subcategory]`

e.g. `BC_EMIS_FOSSIL`, `SOX_OT`, `CO2_CONC`

- for simpler models, the subcategories aren't necessary, however for MAGICC they are so I think we have to include them in this repository
    - for MAGICC, I propose categories of `FOSSIL` (fossil and industrial emissions), `AFOLULUC` (agriculture, fossil, land-use and land-use change which is its `B` category as far as I can tell), `AIR` (emissions from aviation), `SHIP` (international shipping emissions) and `BUNKERS` (the sum of `AIR` and `SHIP` for those users who don't have `AIR`/`SHIP` detail)
- all uppercase as case sensitivity is a pain and doesn't fit with MAGICC anyway as FORTRAN is case insensitive
- '_' as a separator to follow CMIP conventions and give us the freedom to use '-' in names if we need/want (although I'd propose stripping all hyphens out of HFC names e.g. only use 'HFC23' rather than 'HFC-23')

**Comment by rgieseke** [comment]
I had started thinking about some unified naming schemes and started `ghgrenamer`:

https://github.com/openclimatedata/ghgrenamer

https://github.com/openclimatedata/ghgrenamer/blob/master/names.yaml

**Comment by swillner** [comment]
Do we really need those as variables? As different models have different variants of these, maybe we should use generic data structures for these. With these we could follow your hierarchy...

**Comment by swillner** [comment]
(no need for the username mentions, I think ;) )

**Comment by mljeffery** [comment]
for the eqw project we've implemented a mini-version of the ghg-renamer. Definitely helpful so far

**Comment by znicholls** [comment]
> I had started thinking about some unified naming schemes and started `ghgrenamer`

So do we just extend this so that it can handle different types of variables too i.e. emissions, concentrations etc.? 

> Do we really need those as variables? As different models have different variants of these, maybe we should use generic data structures for these.

I don't know what a generic data structure is but I'm sure this is sensible. My thinking was that we want to be able to give this API to non-simple climate model specialists. Hence we should translate all the different models' variants of these into one common language, so non-specialists only need to learn one convention, not one for every model.

**Comment by znicholls** [comment]
Thinking about it more, it might be a good idea to build on top of the [pyam](https://github.com/IAMconsortium/pyam) dataframe. They've done some really nice stuff with filtering and aggregating (and checking those aggregations) that makes life much easier. If we just followed their naming style with these '|' separators to indicate sub-categories, we could reuse all of it...

**Comment by swillner** [comment]
superseeded by #22
