### ISSUE TITLE
Deploy workflow is broken

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#159]
See https://github.com/openclimatedata/openscm/runs/120383160

This should have identified the branch as master, but instead identifies it as HEAD so everything stops. I've just done this pre-release by hand instead.

**Comment by swillner** [comment]
sorry for that. had the same problem in pyhector and fixed it there. since this only affects releases i haven’t pushed the fix here yet. will do in a week, ok?

**Comment by znicholls** [comment]
ye no rush
