### ISSUE TITLE
Define low-level API

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#16]
started in [api-draft](https://github.com/openclimatedata/openscm/tree/api-draft) branch...
shall we use GitHub Projects for this?

**Comment by swillner** [comment]
Projects bundle issues: https://help.github.com/articles/about-project-boards/

So we might have the projects:
- Standardization
- Implementation
- Adapter Implementation
- Organization
- Tests

**Comment by znicholls** [comment]
Happy either way
