### ISSUE TITLE
Views return units of parameter, not units of the view

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#177]
Bug in `core-implementation` branch, also present in `master` I think.

**Describe the bug**

The view should return its units, not the units of the underlying parameter. See test below.

**Failing Test**

```python
# do for both scalar and timeseries views
from openscm.core.parameterset import ParameterSet
def test_unit_view():
    p = ParameterSet()
    v1 = p.scalar('example', 'kg')
    v1.value = 2
    assert v1.unit == 'kg'
    v2 = p.scalar('example', 'g')
    assert v2.value == v1.value * 1000
    assert v2.unit == 'g'
```

**Screenshots**

**System (please complete the following information):**

 - OS: macOS
 - Python and openscm commit/version: Python3.7 commit 1921c09e3a8b1d7d97b99dfbf53323434f494992

**Additional context**

**Comment by znicholls** [comment]
@swillner do you agree?

**Comment by swillner** [comment]
Oh, yes, that's right.
