### ISSUE TITLE
Minimal Python version in Makefile

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#182]
As reported in #75 the Makefile currently doesn't check for a required minimal Python version.

Maybe we should add a version check for the call of `python3`?

At least 3.5 is no longer supported, not sure about 3.6 anymore. Thoughts @swillner @znicholls?

**Comment by swillner** [comment]
Let's stick to 3.7+ as the most common python3 version (and this is the version we test against)

**Comment by swillner** [comment]
we should probably enforce that via the setup.py: https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py#48777286

**Comment by rgieseke** [comment]
Then we can just change the Python version in the Makefile to `python3.7`

**Comment by swillner** [comment]
we should include `python_requires=">3.7"`, shall I do so in #146 ?
