### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#2]
One could consider to have the used models be optional installs (like Matplotlib in Pandas) -- that would avoid having it unusable when someone can't install Pyhector's dependencies.

Disadvantage, versions might be different from what OpenSCM expects, would require some checking of version.

**Comment by znicholls** [comment]
Could make an interactive install script...? 

Also we should add a Makefile (I'll make an issue now)

**Comment by swillner** [comment]
Hmm, I suppose we have two options here:
1. Have an `openscm` core package and for each model a package, e.g. `openscm-magicc`, containing the adapter, in this case for MAGICC
2. Include all adapters in the `openscm` package and have each adapter try to import the respective package, e.g. `pymagicc`, and fail if used without the package available.
I think, I would prefer the second option and also have a `register_model` function for all core models in `openscm` (checking which are actually available), which could also be used by other people writing their own adapter without pushing it into `openscm`.

**Comment by rgieseke** [comment]
+1 for option "2" 

Extra packages might increase installation troubles and debugging other people's installation problems.
