### ISSUE TITLE
Define standard parameter hierarchy

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#22]
Parameters (scalar values or time series) are organized in a hierarchy. Independent from the implementation itself, OpenSCM defines a standard hierarchy that its model adapters should adhere to and end-users can rely on.

In documentation and probably in the standard file format, the hierarchical levels are separated by |, e.g., “Emissions|CO2|Land use”.

**Comment by swillner** [comment]
Please also mention example units for each parameter (OpenSCM should be agnostic about the specific unit) to collect which units should be supported by the unit converter, #23

**Comment by swillner** [comment]
Reminder: Especially define which *type of unit* each parameter expects and which baseline it shoudl refer to if applicable (see #45)

**Comment by znicholls** [comment]
Bits of the parameter space to think about (copied from #96)

- gas species
- sectors
- regions/spatial dimensions

**Comment by swillner** [comment]
Also define which parameters should be read in `Adapter._initialize_run_parameters` and which in `Adapter._initialize_model_input` (see #104)

From #104, @znicholls :

> I can't think of the right words to use to make the distinction between scenario specific stuff (e.g. emissions) and run specific stuff (e.g. ECS). I'm not sure that 'run parameters' and 'model input' is very clear. @rgieseke @chrisroadmap how would you distinguish between stuff that changes every run and stuff the changes once every, say, 600 runs when doing an ensemble of runs?
