### ISSUE TITLE
List of common units

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#28]
@znicholls has a list, will put somewhere ...

**Comment by znicholls** [comment]
have a look at #35

**Comment by swillner** [comment]
We also need at least a paragraph on the units we accept as standard (SI + the gases)

**Comment by znicholls** [comment]
> the units we accept as standard

The units we expect, or something else?

**Comment by swillner** [comment]
Should be included in #22, i.e., there defining which *kind* of unit is expected.
