### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#4]
Even our simple climate models have a lot of config options. My question is, how do we offer access to all those config options, document what they do, keep it all in one place and avoid having functions which take parameter lists 100 items long?

@rgieseke @swillner (should probably also tag Jared and Chris here...) do you know how these command line programs with a billion arguments do it? Could we do something similar?

If you want to see my thinking, here it is. The obvious start is to just have your `run` function contain a whole bunch of keyword args and decent docstrings but that quickly becomes unworkable, especially if you want to do validation e.g.

```python
def run(
     scenario,
     para_1=2.4,
     para_2=3.5,
     ...
     para_110 = 7.6):
     """
     Run a scenario with model X

     # Inputs
     scenario (DataFrame): scenario to run in a df formatted like...

     para_1 (float): parameter 1
     ...
     para_110 (int): switch to turn off carbon cycle, interacts with para_109 and para_108
     """
     # assign all the parameters somehow for later use
     self._para_1 = para_1
     self._para_2 = para_2
     ...
     self._para_100 = para_100
     self._validate()  # somehow check the parameters are ok

def _validate(self):
    # all the validation goes here, but you need to repeat the info in your docstring
    # a long way away from where it is written...
```

We could also store all the default configs in a `yaml` file, let the user call `run` with `run(scenario, paras)` where `paras` is a dict and use something like `marshmallow` (https://marshmallow.readthedocs.io/en/3.0/) to do the validation of the `paras` against the defaults. Here I don't see how you keep validation and docs in one place/how you generate the docs (maybe thin wrapper to read in the `yaml`?...)...

Maybe the answer is that you just need a good test that makes sure that anything which isn't expected raises an error, so everytime you add something new, you have to make sure you did it on purpose? That at least makes sure that you remember to update all the required bits (docstrings, validation) when adding a new para even if it doesn't solve the problem of potential duplication/distance between where a para is validated and where it is used.

Anyway, one I'm sure there is a solution for but I have no idea

**Comment by rgieseke** [comment]
Validation would be super nice, i just think even getting *all* params from three models into one consistent framework would be a huge task. Maybe there is a way to start with the most important ones.

**Comment by znicholls** [comment]
So I'm not sure we want to try to get all the parameters into one consistent framework (at least not initially). As you say, let's start with the most important 3-5? Then go from there. 

It would be nice to be able to pass parameters through the `openscm` interface to the models (or maybe have the `openscm` interface be able to query the models for their parameters?)

**Comment by swillner** [comment]
In the API draft I suggest we use generic `set_parameter`-like functions. These use parameter/timeseries names we define for OpenSCM, which are then read by the model adapters, which know which and how the particular model expects their input... Will document that soon in the [api-draft](https://github.com/openclimatedata/openscm/tree/api-draft) branch...

**Comment by swillner** [comment]
The low-level API will be used to push (set) parameter values from the user side and pull (get) relevant parameter values from the model side. Missing or mal-formatted but mandatory parameters (that cannot be converted) then lead to an error.
