### ISSUE TITLE
Relative units

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#45]
@rgieseke @znicholls 
What do we do about units relative to a baseline, e.g., "Temperature difference to 1961-1990" vs "Temperature difference to 1850-1900"?

**Comment by znicholls** [comment]
Output processing, doesn't belong in the internals I don't think?

**Comment by swillner** [comment]
@rgieseke suggested we define the baselines in the OpenSCM standard and the model adapters have to take care of that. I think, that's a good idea.

**Comment by znicholls** [comment]
I'm missing something. What is the use case where adapters need to know about baselines? Are we expecting people to do temperature driven runs?

**Comment by swillner** [comment]
The DICE climate component, for instance, seems to use relative variables such as "concentration" (I think, total CO2 in the atmosphere is meant) relative to a baseline. So adaptars should take care of both conversions: from input and to output variables.

**Comment by znicholls** [comment]
ah, and we always report relative to 1850-1900? What about deciding what pre-industrial CO2 concentrations? Adaptors look at inputs then decide?

**Comment by swillner** [comment]
I think, it's enough if we document that in our standard (#28)...

**Comment by znicholls** [comment]
beauty

**Comment by swillner** [comment]
Closing and adding references in the relevant standardization/documentation issues
