### ISSUE TITLE
monthly short telecalls?

### ISSUE THREAD

**Issue by gidden** [openclimatedata/openscm#55]
@rgieseke and I are sitting at IAMC and thought it might be helpful to have short (10-15) telecalls ~1/month to keep up the discussion on pyam/openscm integration. Whatcha think @znicholls? others?

**Comment by rgieseke** [comment]
Maybe decemberish on https://github.com/IAMconsortium/pyam/issues/126

**Comment by znicholls** [comment]
should we go for the week dec 17-21, or is that too far into silly season?

**Comment by chrisroadmap** [comment]
If you guys are happy for me to join in, then Dec 17-21 is about the only
time I can do :)

**Comment by rgieseke** [comment]
Sounds good!

**Comment by gidden** [comment]
I can do it at the beginning of that week!

**Comment by gidden** [comment]
Hi all, how do we feel about Tuesday, December 14 at 11AM CEST?

**Comment by znicholls** [comment]
> Tuesday, December 14

Tuesday December 11?

**Comment by gidden** [comment]
Even worse! Tuesday, December 18 =). My apologies.

**Comment by znicholls** [comment]
Tuesday, December 18 at 11AM CEST is fine for me although if we could go earlier that is better for aussies (being the minority, I will bend)

**Comment by gidden** [comment]
Unfortunately, I have meetings from 9-11 =(

**Comment by chrisroadmap** [comment]
I will join in on this and will resolve to read the last two months of issue tracking before then :)

**Comment by gidden** [comment]
Looks like the call is now at 12 based on the invite. That's actually
better for me (a seminar was scheduled for 11....)

**Comment by znicholls** [comment]
@lewisjared

**Comment by gidden** [comment]
Now that we have established the calls, I think it's safe to close this!
