### ISSUE TITLE
Docs shortcuts

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#62]
Shall we have a file in docs which has all our common shortcuts/links? I'm thinking links for OpenSCM and perhaps a shortcut for CO2 so when we write e.g. "|CO2|" in our docstrings, it will render as "CO<sub>2</sub>"

**Comment by swillner** [comment]
Had to move that directly into `docs/conf.py` (otherwise recursive inclusion into the shortcuts file itself)

**Comment by znicholls** [comment]
> Had to move that directly into `docs/conf.py` (otherwise recursive inclusion into the shortcuts file itself)

Is it in there?

**Comment by swillner** [comment]
```
rst_epilog = """
.. |CO2| replace:: CO\ :sub:`2`\
"""
```
(22-parameter-hierarchy branch)

**Comment by znicholls** [comment]
nice! didn't realise it wasn't in master yet...

**Comment by swillner** [comment]
almost ;)

**Comment by swillner** [comment]
(just moved your shortcut from the extra file in there)
