### ISSUE TITLE
ParameterSet: Model run mode

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#63]
**Is your feature request related to a problem? Please describe.**

At the moment there is no way for us to specify the run mode for models. Here I am thinking emissions driven, concentrations driven, a hybrid of the two etc.

**Describe the solution you'd like**

Some way to do this. I have no idea about the best implementation yet. 

**Describe alternatives you've considered**

We could leave it so users always have to use the right combination of model specific parameters to achieve what they want. I feel that is against the spirit of the project...

**Additional context**

There is no rush on this, it's more of a nice to have rather than an essential right now.

**Comment by swillner** [comment]
Hmm, should we define that as a parameter in the `ParameterSet`? Or define a set of standard options?

**Comment by znicholls** [comment]
> should we define that as a parameter in the `ParameterSet`?

I like this, and make it a condition of any adapter that they can handle a string parameter (we'll need a new parameter type) called something like `run_mode`.

**Comment by swillner** [comment]
Probably replaced by #124 ?
