### ISSUE TITLE
In-code parameter names

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#64]
When writing models, should we copy parameter names straight out of papers or should we use standard coding practices?

For example, when writing the adapter for [Petschel-Held 1999](https://doi.org/10.1023/A:1005487123751), do we write emissions as `E` (as in the paper) or `e` (following Python conventions) or as `emissions` (giving it an easier name to immediately understand) or something else? An example of something else would be to provide access to all variables via the names as they are given in their respective papers (e.g. `ph99.E`), but use Python compliant names internally. This allows external users to query things just by copying the paper, but allows us to write code we can actually work with easily.

**Comment by znicholls** [comment]
@njleach @billbwu @stujen thoughts also welcome

**Comment by chrisroadmap** [comment]
Well, I think there is always a difference between variables written in equations in papers, which tend to be single symbols, and those in computer code that can be more descriptive. For code I think I would prefer descriptive names that are equivalent between SCMs, so `emissions` means the same thing in FaIR, MAGICC, etc. Another reason is that `E` could stand for a number of things (efficacy, effective radiative forcing, energy...) so reduces ambiguity.

**Comment by swillner** [comment]
I think this issue applies only inside an adapter and only when writing one. The "communication to the outside" only happens via the `ParameterSet` where we use the OpenSCM standard parameters (#22). So I think, we can close this for now?

**Comment by znicholls** [comment]
> So I think, we can close this for now?

I'd prefer not as I think it's still a live discussion and one we can revisit when writing our implementations of simple models e.g. AR5IR, DICE climate component, PH99

**Comment by znicholls** [comment]
Thinking again, I think we can close this. In #60 I follow the general principle discussed here: names from `ParameterSet` follow the conventions defined by OpenSCM whilst I try to use more descriptive names for model parameters in the `PH99Model` implementation.
