### ISSUE TITLE
Model unit handling

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#65]
In #60 we have the chance to write a model in our idea of the ideal way. That raises an opportunity but also some questions. In this issue, the discussion is about how models should handle units internally. For ease, I would favour writing in a way that means the model only takes in Pint arrays (forcing users to assign units before passing into the model and getting people to see what Pint is). Another consequence of this is that internal processing becomes super easy as you don't have to do any unit checking and if people get their input units wrong, dimensionality errors will be thrown. However, there are obviously other ways to do this with obvious cons of my suggestion being that relying in Pint means we don't have a language agnostic suggestion (or our suggestion is to build a units library for whatever language before you start) and potentially a speed hit (although that one I am less clear on as Pint can use numpy under the head so might actually not cost you much...).

**Comment by swillner** [comment]
I think, inside OpenSCM we should leave the unit handling to OpenSCM and request the units from the core as we want them in the model as that's one of the purposes of OpenSCM...

**Comment by swillner** [comment]
Ah, ok ;) Then, I think, forcing users to provide parameters/input data with units is a good idea in general. i am afraid, we can't find a language-agnostic way of handling units, or at least no easy one. However, inside OpenSCM, I hope, we found a good way of dealing with that issue for now.

**Comment by znicholls** [comment]
Sounds good!

**Comment by znicholls** [comment]
In #60 I've built our `PH99Model` implementation entirely around Pint. It's an example of how things can be done but I still think the OpenSCM way (entirely based on views) is better if people can use it.
