### ISSUE TITLE
Interface with Pyam

### ISSUE THREAD

**Issue by danielhuppmann** [openclimatedata/openscm#68]
This issue is fleshing out the discussion in #52 with a concrete (but stylized) example drawn from the SR15 workflow, as just discussed via zoom with multiple openscm developers.

Proposed workflow and interface
====================

Starting point
--------------

Model results from an IAM stored as a `pyam.IamDataFrame`. Input to `openscm` would be a `pd.DataFrame` like

| **model**    | **scenario**    | **region** | **variable**   | **unit** | **year** | **value** |
|--------------|-----------------|------------|----------------|----------|----------|-----------|
| MESSAGEix    | LowEnergyDemand | World      | Emissions\|CO2  | Mt CO/yr | 2010     | 38542.04  |
| MESSAGEix    | LowEnergyDemand | World      | Emissions\|CO2  | Mt CO/yr | 2020     | 39563.51  |
| ...          | ...             | ...        | ...            | ...      | ...      | ...       |

Emissions variables in IAMC usually conform to the following notation convention, but level of detail and scope of emissions covered differs by project and model.

`Emissions|CO2`
`Emissions|CO2|AFOLU`
`Emissions|CO2|Energy`
`Emissions|CO2|Energy|Demand`
`Emissions|CO2|Energy|Demand|Industry`
`Emissions|CO2|Energy|Demand|Residential and Commercial`
`Emissions|CH4`
`Emissions|CH4|Energy`
`Emissions|CH4|AFOLU`
`Emissions|F-Gases`
`Emissions|Kyoto Gases`
`Emissions|N2O`
`Emissions|N2O|Energy`
`Emissions|N2O|AFOLU`
`Emissions|Sulfur`
`Emissions|BC`

Expected output
-----------------

Ideally (from an IAM user perspective), `openscm` returns a `pd.DataFrame` like the following, which can then be appended to the original `IamDataFrame`.

| **model**    | **scenario**    | **climate_model** | **region** | **variable**                   | **unit** | **year** | **value** |
|--------------|-----------------|-------------------|------------|--------------------------------|----------|----------|-----------|
| MESSAGEix    | LowEnergyDemand | MAGICC6         | World      | Temperature\|Global Mean | Mt CO/yr | 2010     | 0.89      |
| MESSAGEix    | LowEnergyDemand | MAGICC6         | World      | Temperature\|Global Mean | Mt CO/yr | 2020     | 0.92      |
| ...          | ...             |                   |  ...       | ...            | ...      | ...      | ...       |

Variables could have the following structure for deterministic assessment:

`Temperature|Global Mean`
`Forcing|CO2`

In probabilistisc assessment, one could either extend the variables like it was done in SR15

`Temperature|Global Mean|Median`
`Temperature|Global Mean|P95`

or add another column with percentiles to the returned dataframe.

API
----

Having a `pyam.IamDataFrame`, ideally we have an API like

`pyam.IamDataFrame.run_climate_model(climate_model, **kwargs)`,

where `**kwargs` can specify e.g. method of infilling of missing data, harmonization method to historical reference data.

**Comment by swillner** [comment]
I suppose, we should define the standard parameters very similar to `pyam` (#22) and then add a `to_iam_dataframe` function to `ScmDataFrame`, @znicholls ?

**Comment by znicholls** [comment]
> I suppose, we should define the standard parameters very similar to `pyam` (#22) and then add a `to_iam_dataframe` function to `ScmDataFrame`, @znicholls ?

Yep, we discussed this on Wednesday and decided that we would publish a list of parameters that are understood by all OpenSCM adapters. Yes any proposed implementation of `ScmDataFrame` will include a `to_iamdataframe` method.

**Comment by swillner** [comment]
>> I suppose, we should define the standard parameters very similar to `pyam` (#22) and then add a `to_iam_dataframe` function to `ScmDataFrame`, @znicholls ? ...

@znicholls Cool. #22 was exactly that all along... (let's just not forget about the older issues)

**Comment by znicholls** [comment]
> #22 was exactly that all along... (let's just not forget about the older issues)

oops yep!
