### ISSUE TITLE
Unit handling

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#8]
See https://github.com/openclimatedata/pymagicc/issues/76 for discussion in Pymagicc

Options include xarray which has unit handling, or looking into Pandas' new ExtensionTypes (http://pandas-docs.github.io/pandas-docs-travis/extending.html#extension-types)

I think it's a huge task and it would be enough to have well documented standards for inputs and outputs (and leave it to users to e.g. ensure CO2_fossil is in GtC).

**Comment by chrisroadmap** [comment]
I've had an initial play and pint looks useful (see unit_fiddle branch). I may go down this route for FaIR.

**Comment by rgieseke** [comment]
That looks good!

Here is what cyberpandas is doing to get units (in this case IP adresses) connected to Pandas DataFrames: https://github.com/ContinuumIO/cyberpandas/blob/master/cyberpandas/ip_array.py#L32

**Comment by znicholls** [comment]
here's the pint issue related to joining pint up with pandas https://github.com/hgrecco/pint/issues/645

It looks fiddly but not impossible so maybe it's time for us to give back?

**Comment by znicholls** [comment]
alright I think we're on the road to somewhere https://github.com/hgrecco/pint/pull/671
