### ISSUE TITLE
Rename OpenSCMDataFrame

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/openscm#82]
@znicholls I probably should have caught this earlier, but I'd suggest to rename `OpenSCMDataFrame` to just `SCMDataFrame` or `ScmDataFrame` (shorter and in line with `IamDataFrame`)

Serves also as a test in which locations such changes would require updates (in Pymagicc) ... might be worth investigating whether we can trigger Pymagicc builds on merging of OpenSCM PRs.

**Comment by znicholls** [comment]
> I'd suggest to rename `OpenSCMDataFrame` to just `SCMDataFrame` or ScmDataFrame (shorter and in line with `IamDataFrame`)

I like it.

> might be worth investigating whether we can trigger Pymagicc builds on merging of OpenSCM PRs

That's possible. Other options would be nightly travis runs (I've seen this done before somewhere). However I think once we have openscm releases that problem goes away as we can pin the openscm version until we're ready to bump it.

**Comment by rgieseke** [comment]
Ok, i'll try a pull request for this :-]

**Comment by rgieseke** [comment]
> Other options would be nightly travis runs (I've seen this done before somewhere). However I think once we have openscm releases that problem goes away as we can pin the openscm version until we're ready to bump it.

If possible we should try to avoid pinning versions as many people work with one big "environment" and then one quickly can run into circular impossible dependencies.

If this ever gets a bigger user base we could have Deprecation notices etc.

Daily (or weekly) Travis builds could be a good idea (also in general to check with e.g. Pandas changes) and maybe GitHub Actions can also do this ...

**Comment by znicholls** [comment]
> If possible we should try to avoid pinning versions as many people work with one big "environment" and then one quickly can run into circular impossible dependencies.

True but I am hopeful this environment will be sufficiently small and sufficiently well used that we avoid this...

> Daily (or weekly) Travis builds could be a good idea (also in general to check with e.g. Pandas changes) and maybe GitHub Actions can also do this ...

Let's assign to you or I in a new issue (up to you who takes it)

**Comment by rgieseke** [comment]
Changed in #83
