### ISSUE TITLE
Clarifying timeseries

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/openscm#95]
@swillner I think we should write a notebook explaining how to set timeseries values for users.

Am I correct in saying:

- if users have flux data (e.g. emissions), they should get a writeable timeseries view with the period length that corresponds to their time steps and then write straight to the view? 
- if users have state data (e.g. concentrations), they should first use `timeframes._calc_interval_averages` to get their data into interval averages, then they should get a writeable timeseries view with the period length that corresponds to their time steps and then write to the view?

**Comment by swillner** [comment]
Superseeded by #125 ;)
